### ISSUE TITLE
Unable to see overview page for specific users

### ISSUE THREAD

**Issue by noisy** [aaroncox/steemdb#1]
I tried to check my account: https://steemdb.com/@noisy and I got this error:

```
View '_elements/tx/convert' was not found in any of the views directory
#0 [internal function]: Phalcon\Mvc\View->_engineRender(Array, '_elements/tx/co...', false, false)
#1 [internal function]: Phalcon\Mvc\View->partial('_elements/tx/co...', NULL)
#2 /var/www/com_steemdb/cache/volt/_var_www_com_steemdb_app_views_account_view.volt.php(266): Phalcon\Mvc\View\Engine->partial('_elements/tx/co...')
#3 [internal function]: unknown()
#4 [internal function]: Phalcon\Mvc\View\Engine\Volt->render('/var/www/com_st...', Array, true)
#5 [internal function]: Phalcon\Mvc\View->_engineRender(Array, 'account/view', true, true, NULL)
#6 [internal function]: Phalcon\Mvc\View->render('account', 'view', Array)
#7 /var/www/com_steemdb/public/index.php(41): Phalcon\Mvc\Application->handle()
#8 {main}
```

![selection_186](https://cloud.githubusercontent.com/assets/201263/17923193/37f93a00-69e3-11e6-86d3-beeb0deb81bf.png)

**Comment by aaroncox** [comment]
Should be working now! I was missing a template for the `convert` operation.
